"use strict";
let myname = document.getElementById("name");
// console.log('myname:',myname);
let desig = document.getElementById("desig");
// console.log('desig:',desig);
let phone = document.getElementById("phone");
// console.log('phone',phone);
let email = document.getElementById("email");
// console.log('email',email);
let add = document.getElementById("add");
// console.log('add',add);
let pass = document.getElementById("pass");
// console.log('pass',pass);
let deg = document.getElementById("deg");
// console.log('deg',deg);
let uni = document.getElementById("uni");
// console.log('uni',uni);
let pass2 = document.getElementById("pass2");
// console.log('pass2',pass2);
let deg2 = document.getElementById("deg2");
// console.log('deg2',deg2);
let uni2 = document.getElementById("uni2");
// console.log('uni2',uni2);
let skill1 = document.getElementById("skill1");
// console.log('skill1',skill1);
let skill2 = document.getElementById("skill2");
// console.log('skill2',skill2);
let skill3 = document.getElementById("skill3");
// console.log('skill3',skill3);
let skill4 = document.getElementById("skill4");
let skill5 = document.getElementById("skill5");
let lang1 = document.getElementById("lang1");
// console.log('lang1',lang1);
let lang2 = document.getElementById("lang2");
// console.log('lang2',lang2);
let styear = document.getElementById("styear");
// console.log(' styear', styear);
let endyear = document.getElementById("endyear");
// console.log(' endyear', endyear);
let company = document.getElementById("company");
// console.log(' company', company);
let companylocation = document.getElementById("companylocation");
// console.log(' companylocation', companylocation);
let jobtittle = document.getElementById("jobtittle");
// console.log(' jobtittle', jobtittle);
let achiv1 = document.getElementById("achiv1");
// console.log(' achiv1', achiv1);
let achiv2 = document.getElementById("achiv2");
// console.log(' achiv2', achiv2);
let achiv3 = document.getElementById("achiv3");
// console.log(' achiv3', achiv3);
let pic = document.getElementById("pic");
let submitbtn = document.getElementById("submitbtn");
console.log("submitbtn", submitbtn);
let form = document.getElementById("form");
form?.addEventListener('submit', (e) => {
    e.preventDefault();
    console.log(myname?.value);
    localStorage.setItem("name", myname.value);
    localStorage.setItem("desig", desig.value);
    localStorage.setItem("phone", phone.value);
    localStorage.setItem("email", email.value);
    localStorage.setItem("add", add.value);
    localStorage.setItem("pass", pass.value);
    localStorage.setItem(" deg", deg.value);
    localStorage.setItem("uni", uni.value);
    localStorage.setItem("pass2", pass2.value);
    localStorage.setItem("deg2", deg2.value);
    localStorage.setItem("skill1", skill1.value);
    localStorage.setItem("skill2", skill2.value);
    localStorage.setItem("skill3", skill3.value);
    localStorage.setItem("skill4", skill4.value);
    localStorage.setItem("skill5", skill5.value);
    localStorage.setItem("lang1", lang1.value);
    localStorage.setItem("lang2", lang2.value);
    localStorage.setItem("styear", styear.value);
    localStorage.setItem("endyear", endyear.value);
    localStorage.setItem("company", company.value);
    localStorage.setItem("companylocation", companylocation.value);
    localStorage.setItem("jobtittle", jobtittle.value);
    localStorage.setItem("achiv1", achiv1.value);
    localStorage.setItem("achiv2", achiv2.value);
    localStorage.setItem("achiv3", achiv3.value);
    if (pic.files && pic.files[0]) {
        let reader = new FileReader();
        reader.addEventListener("load", () => {
            let textImg = reader.result;
            console.log(textImg);
            localStorage.setItem("pic", textImg);
        });
        reader.readAsDataURL(pic.files[0]);
    }
    window.location.href = "./resume/index.html";
});
